### ISSUE TITLE
Two Suggestions about this Project

### ISSUE THREAD

**Issue by Liskelleo** [yjg30737/pyqt-editable-treewidget-example#1]
Hi, there. Recently I've been working on the QTreeWidget in PyQt5. And your project give me some great inspirations which I would appreciate. Here are some ideas that came through:
1) How to make it editable within more than one single column?
2) How to allow users to partially edit the content of the widget? For instance, they cannot edit header labels and the label of the first parent attribute but can actually edit the rest parts. Can this goal be achieved by presetting parameters in the class `EditableTreeWidget`?
3) Noticed that you've set the `ContextMenuPolicy` to `Qt.ActionsContextMenu`, how to save the change by users?
Looking forwards to your early reply^^

**Comment by yjg30737** [comment]
Hello :)

<b>First</b> one takes a lot of time to do it, since we cannot get the updated value from the qtreewidgetitem.

i can't make it by making child class of qtreewidgetitem to add the signal because qtreewidgetitem is not from qobject.

So rename something at once needs a different method. I give you this though: self.selectionItems()

<b>Second</b> one is thankfully working well by using recursive function. You can just clone my recent repository to check that out.

<b>Third</b> one is.. i can't fully understand what you said so i need more information. I assume the thing you want to save is QTreeWidget's hierarchy, but what kind of form do you want to convert it into?

**Comment by Liskelleo** [comment]
Glad to hear your reply;) Here’re my opinions:

For the first point, I can’t get you thoroughly, do you actually mean that by using  selectionItems() can get the selected items after being renamed by users and then by using methods like currentItem().setText()    to update?

Secondly, your new work seems not to work well for me because when double-clicking certain items, they automatically switched to the mode of modification.

Last one, I actually want to save QTreeWidget's hierarchy in order to reset it when users open it again. So what kind of form to convert it into may not count as long as users’ changes on it can be saved and reuse.

**Comment by yjg30737** [comment]
First one is just a matter of time. I didn't take much time to do it so i have to check it out once more.

Second one is.. i don't know. Could you clarify for me again? I understand your second request as "make it unable to change the QTreeWidgetItem's name if it has at least one child".

You have to check the checkbox next to the QTreeWidget to make it work. UI is updated but i've not updated in my README.md

I got the third one so it can be done with dictionary or other method and i can save it with hierarchy.ini or something like that with QSettings.

I will check those things out next day. I'm currently busy :)

**Comment by yjg30737** [comment]
I found that second one was working but it was actually flawed, So i've just fixed it. Check it out

**Comment by yjg30737** [comment]
OK, for the first one:

![image](https://user-images.githubusercontent.com/55078043/221758852-dc5ee59c-9cfb-4f07-94b1-f4a1e1e702e9.png)

I've somehow never got your request in the first place, i thought you've said that you want to change multiple "items", not columns.

Why did i miss that point? silly me.

OK, i assume this is the point of what you've said.

So, how to make it editable more than one single column? Actually you can click manually to change it. But that is not obviously you want to hear.

Pressing enter from the first column to focus on the second column is on my mind, but sorry to say the demand is kinda abstract. I need your purpose(doesn't need to be detailed) to do so or similar application which can operate like that as an example.

I'm working on third one. btw

**Comment by Liskelleo** [comment]
I’m so sorry for my late reply. My thoughts can be summed up to the aim to preset some FIXED items that can not be renamed ahead and to add some FLEXIBLE items that can be renamed and users’ changes can be saved and when the next time users open the widget, the modified contents can be shown. As for the “more than one column” thing, I meant that the widget HAS more than one column and that’s it. Thanks for your works, I really mean it;)

**Comment by yjg30737** [comment]
No problem 👌🙂

I've just completed the third one. Keep in mind, it won't work if there are at least two items shared the same name in the same hiearchical level. Because i convert the QTreeWidget into Python dictionary to save it and dictionary doesn't allow to save the multiple keys.

I got that! Then i need to add the multiple columns in case of the people who need that. That actually can significantly change the second and third one. But i hope that's not the case.

I cannot do it right away. please wait :)

**Comment by Liskelleo** [comment]
You can keep your previous functions and I think they’re still meaningful. Btw, what you’ve done is amazing enough and every time I can learn a lot from your work^^

**Comment by yjg30737** [comment]
Good to hear, thanks to the compliment. You can still feel free to ask something to me if those functions are not enough. I personally keep it as well. 🙂

**Comment by Liskelleo** [comment]
So if you’ve done the rest part of the work in your spare time, don’t hesitate to let me know. Best wishes!

**Comment by Liskelleo** [comment]
Oops, when I cloned your recent repository to check, something went wrong for the first run:
```
Traceback (most recent call last):
  File "C:\Users\***\Desktop\editableTreeWidgetExample.py", line 248, in <module>
    example = MainWindow()
  File "C:\Users\***\Desktop\editableTreeWidgetExample.py", line 133, in __init__
    self.__initUi()
  File "C:\Users\***\Desktop\editableTreeWidgetExample.py", line 174, in __initUi
    self.__load()
  File "C:\Users\***\Desktop\editableTreeWidgetExample.py", line 210, in __load
    data = eval(self.__settings_struct.value('dict'))
TypeError: eval() arg 1 must be a string, bytes or code object
```

**Comment by yjg30737** [comment]
That was simple. The error occurs because the given argument of the eval was "None" since there is no ini file or dict attribute at all at the first time.

I should've checked that as well.  Now it works

**Comment by Liskelleo** [comment]
Hi, there. So now the hierarchy of this widget can be saved in terms of dictionary, and I wonder how to preset some FIXED items which can't be renamed? Which means that the rest items can be created and modified freely by users and those fixed ones always remain the same once they were preset.

**Comment by yjg30737** [comment]
I changed up a bit.

The FIXED(which means should not be able to be renamed) property is now saved as well.

You can even fix certain item in the context menu.

**Comment by Liskelleo** [comment]
Okay, I've checked your update and it works out fine. Thx^^

**Comment by yjg30737** [comment]
yup :)

**Comment by Liskelleo** [comment]
Hi, I know there’re still three testing parts of this project and I wonder that whether or not you would complete them in the future, in the case of your answer “yes” I will close this issue with “completed” choices and keep following with your further updates. So please let me know about your plans;)

**Comment by yjg30737** [comment]
Current week is really busy 😅. I will take care of it this weekend!

**Comment by Liskelleo** [comment]
No hurry then;)

**Comment by Liskelleo** [comment]
It seems that this project's almost complete. Then I shut the issue section ;)

**Comment by Liskelleo** [comment]
It seems that this project's almost complete. Just three point of my views:
1) The first is about the "ExtendedSelection" mode, which should be adapted to the function of deleting items, that means that when getting more than one item that selected by users under the "ExtendedSelection" mode, users can press `delete` key to delete them all instead of deleting the first item of all selected items.
2) It seems that the "KeyBindingWidget" can not be displayed correctly on my computer like this, I wonder whether you have frozen the widget due to this fuction is still under testing.
3) Still wonder about your "Allow duplicated name" mode, could you please give me some introdution of this function?
![image](https://user-images.githubusercontent.com/97718634/229024347-1d374d38-045d-496d-b4d7-a9b5687fd427.png)

**Comment by yjg30737** [comment]
Sorry for my belated reply 😥 It's been a while :)

step by step answer:

1. I fixed it. I tested it very loosely though..
2. That is indeed under testing. Because of that, it is disabled so you can't change the key command or scroll it.
3. "Allow duplicated names" indicates that attributes with the same name can exist at the same level of the tree. It must be confusing to someone that the attributes carrying the same name exists.

I've been very busy cause the deadline of my company project is near and some of my personal project, but i will definitely check that out soon enough.

**Comment by Liskelleo** [comment]
Thanks a lot for your patient reply, even though you are fully engaged presently :)
The last two points are clear enough for me now, however, there might be a little problem in the first point: when getting currentItem() as 'NoneType' object under the multi-seletion mode, it may raise AttributeError: 'NoneType' object has no attribute 'addChild'. So I've just modified it as below ;)
```
    def addChildAttr(self, text=None):
        text = 'New Attr' if not text or isinstance(text, bool) else text
        item = EditableTreeWidgetItem()
        item.setText(0, text)
        item.setFlags(item.flags() | Qt.ItemIsEditable)
        if self.currentItem() is not None:  # add a judging statement
            self.currentItem().addChild(item)
            self.setCurrentItem(item)
            self.editItem(item, 0)
            if self.__parentItemShouldNotChangedFlag:
                item.parent().setFlags(item.flags() & ~Qt.ItemIsEditable)
```
Btw, no need to hurry and best wishes!

**Comment by yjg30737** [comment]
that's great one, thanks for that :)

**Comment by Liskelleo** [comment]
Np ;)

**Comment by Liskelleo** [comment]
So far so good, any new updates may help in the future.
